export const ADDRESS_LIST_REQUEST = 'ADDRESS_LIST_REQUEST';
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS';
export const ADDRESS_LIST_FAIL = 'ADDRESS_LIST_FAIL';

export const ADDRESS_CREATE_REQUEST = 'ADDRESS_CREATE_REQUEST';
export const ADDRESS_CREATE_SUCCESS = 'ADDRESS_CREATE_SUCCESS';
export const ADDRESS_CREATE_FAIL = 'ADDRESS_CREATE_FAIL';

export const SET_SHIPPING_ADDRESS = 'SET_SHIPPING_ADDRESS';

export const ADDRESS_REMOVE_REQUEST = 'ADDRESS_REMOVE_REQUEST';
export const ADDRESS_REMOVE_SUCCESS = 'ADDRESS_REMOVE_SUCCESS';
export const ADDRESS_REMOVE_FAIL = 'ADDRESS_REMOVE_FAIL';

