export const CART_GET_REQUEST = 'CART_GET_REQUEST';
export const CART_GET_SUCCESS = 'CART_GET_SUCCESS';
export const CART_GET_FAIL = 'CART_GET_FAIL';

export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST';
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS';
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL';

export const CART_UPDATE_ITEM_REQUEST = 'CART_UPDATE_ITEM_REQUEST';
export const CART_UPDATE_ITEM_SUCCESS = 'CART_UPDATE_ITEM_SUCCESS';
export const CART_UPDATE_ITEM_FAIL = 'CART_UPDATE_ITEM_FAIL';

export const CART_DELETE_ITEM_REQUEST = 'CART_DELETE_ITEM_REQUEST';
export const CART_DELETE_ITEM_SUCCESS = 'CART_DELETE_ITEM_SUCCESS';
export const CART_DELETE_ITEM_FAIL = 'CART_DELETE_ITEM_FAIL';
